apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-service-api-deployment
  namespace: peerprep
  labels:
    app: docs-service-api
spec:
  selector:
    matchLabels:
      app: docs-service-api
  template:
    metadata:
      namespace: peerprep
      labels:
        app: docs-service-api
    spec:
      containers:
        - name: docs-service-api
          image: ghcr.io/cs3219-ay2324s1-g04/peerprep_docs_service_api
          ports:
            - containerPort: 9007
          env:
            - name: REDIS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: docs-service-redis-client-config-map
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docs-service-redis-client-secret
                  key: redis-password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: docs-service-redis-client-config-map
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: docs-service-redis-client-config-map
                  key: redis-port
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: docs-service-redis-client-config-map
                  key: redis-db
            - name: MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-user
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docs-service-mq-client-secret
                  key: mq-password
            - name: MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-host
            - name: MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-port
            - name: MQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-vhost
            - name: MQ_SHOULD_USE_TLS
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-should-use-tls
            - name: MQ_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-exchange-name
            - name: MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: docs-service-mq-client-config-map
                  key: mq-queue-name
            - name: QUESTION_SERVICE_API
              value: http://question-service-api-service:9001/question-service
            - name: DOCS_SERVICE_PORT
              value: '9007'
            - name: DOCS_SERVICE_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: docs-service-api-config-map
                  key: docs-service-route
            - name: NODE_ENV
              value: production
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
