apiVersion: v1
kind: Service
metadata:
  name: docs-service-api-service
  namespace: peerprep
spec:
  selector:
    app: docs-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9007
      targetPort: 9007
